dependencies:
- alias: expose
  name: exposecontroller
  repository: https://chartmuseum.build.cd.jenkins-x.io
  version: 2.3.58
- alias: cleanup
  name: exposecontroller
  repository: https://chartmuseum.build.cd.jenkins-x.io
  version: 2.3.58
- name: front-end
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.9
- name: node-http-quickstart
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.12
